# Generated by Django 3.2 on 2022-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentadminuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
