# Generated by Django 3.2 on 2022-04-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_alter_departmentadminuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='departmentadminuser',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.department'),
        ),
        migrations.AlterField(
            model_name='departmentadminuser',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.usertype'),
        ),
    ]
