# Generated by Django 3.2 on 2022-04-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_auto_20220417_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentadminuser',
            name='departments',
        ),
        migrations.AddField(
            model_name='department',
            name='assigned_dept',
            field=models.ManyToManyField(to='report_app.DepartmentAdminUser'),
        ),
    ]
