# Generated by Django 3.2 on 2022-04-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_auto_20220417_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadminuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
