# Generated by Django 3.2 on 2022-04-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_departmentadminuser_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departments',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='assigned_dept',
        ),
        migrations.AddField(
            model_name='departmentadminuser',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report_app.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departmentadminuser',
            name='usertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_app.usertype'),
        ),
    ]
