# Generated by Django 3.2 on 2022-04-23 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_app', '0007_auto_20220419_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentadminuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='departmentadminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='departmentadminuser',
            name='username',
        ),
        migrations.AddField(
            model_name='departmentadminuser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
